version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: BeerCatalogueAPI
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/static/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/BeerCatalogueAPI
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8081:8081"