apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beer-catalogue
  template:
    metadata:
      annotations:
        date: "{{ now }}"
      labels:
        app: beer-catalogue
    spec:
      containers:
        - name: beer-catalogue
          image: beer-catalogue:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: beer-catalogue-service
spec:
  type: NodePort
  selector:
    app: beer-catalogue
  ports:
    - port: 8081
      targetPort: 8081