apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
data:
  url: {{ required "database.credentials.url is required" .Values.database.credentials.url | b64enc | quote }}
  username: {{ required "database.credentials.username is required" .Values.database.credentials.username | b64enc | quote }}
  password: {{ required "database.credentials.password is required (pass it with --set database.credentials.password=...)" .Values.database.credentials.password | b64enc | quote }}
