apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
data:
  url: {{ .Values.database.credentials.url | b64enc | quote }}
  username: {{ .Values.database.credentials.username | b64enc | quote }}
  password: {{ .Values.database.credentials.password | b64enc | quote }}